[package]
name = "simple-send"
version = "0.1.0"
authors = ["nph278 <carllegrone@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
local_ipaddress = "0.1.3"
